#!/usr/bin/env ansible-playbook
- import_playbook: server-full.yaml

- hosts: localhost
  tasks:
    - include: tasks/packages_from_file.yaml
      vars:
        filename: andy
    - name: Install Nerd Fonts
      include_tasks: tasks/fonts.yaml
