#!/usr/bin/env ansible-playbook
- import_playbook: desktop.yaml

- hosts: localhost
  tasks:
    - include: tasks/packages_from_file.yaml
      vars:
        filename: andy
    - name: Install Mailspring
      apt:
        deb: https://updates.getmailspring.com/download?platform=linuxDeb
    - name: Install Slack
      include_tasks: tasks/slack.yaml
    - name: Install Zotero
      include_tasks: tasks/zotero.yaml
    - name: Install Discord
      include_tasks: tasks/discord.yaml
